version: '3.3'

services:

  cassandra-seed:
    container_name: cassandra-seed-node
    image: cassandra:latest
    ports:
      - "9042:9042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"


#  cassandra-node-1:
#    image: cassandra:latest
#    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
#    environment:
#      - "CASSANDRA_SEEDS=cassandra-seed-node"
#    depends_on:
#      - "cassandra-seed"
#
#
#  cassandra-node-2:
#    image: cassandra:latest
#    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
#    environment:
#      - "CASSANDRA_SEEDS=cassandra-seed-node"
#    depends_on:
#      - "cassandra-seed"
